apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-nginx-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-nginx
  template:
    metadata:
      labels:
        app: react-nginx
    spec:
      containers:
        - name: react-nginx
          image: react-nginx-app:latest  # Ensure this image is built
          imagePullPolicy: Never  # Prevents Kubernetes from trying to pull from Docker Huband available
          ports:
            - containerPort: 80
